### PR TITLE
fixed the bug that pop(0) doesn't work

### PR DESCRIPTION
**Pull request by kyay**
fixed the bug in python when you try to use pop(0), the fix just checks if the number is zero or not

### CODE REVIEW

**Comment by kyay** [comment]
@nwinter 
can you please review this change and merge it if it is good

**Comment by nwinter** [comment]
Looks fine to me, but I'm not that familiar. @differentmatt ?

**Comment by differentmatt** [comment]
Thanks @kyay!

**Comment by kyay** [comment]
you're welcome, i am glad i helped

**Pull request merged**
